minecraft_version=26.1.2
neoforge_version=26.1.2.108
ae2_version=26.1.11-beta
mod_id=ae2virtualwell
mod_name=AE2 Virtual Well
mod_license=MIT
mod_version=1.0.4
mod_group_id=de.project.ae2virtualwell
mod_authors=Gener
mod_description=A generative liquid and fluid storage cell addon for Applied Energistics 2.

loader_version_range=[1,)
neo_version_range=[26.1.2.108,)
minecraft_version_range=[26.1.2,26.2)
ae2_version_range=[26.1.11-beta,27.0.0)

org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
